name: continuous integration workflow

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

  jobs:
    # Run tests and make sure everything works
    run-test:
      runs-on: ubuntu-22.04

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven

        - name: Run test with maven
          run: mvn test